version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - main: cmd/anka-cloud-gitlab-executor/main.go
    ldflags: >
      -X github.com/veertuinc/anka-cloud-gitlab-executor/internal/version.version={{.Version}}
      -X github.com/veertuinc/anka-cloud-gitlab-executor/internal/version.commit={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - arm64
      - amd64
    binary: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}

archives:
  - format: binary
    builds_info:
      mode: 0755
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}