pipeline {
    agent { node {
            label 'cloud_container_host'
        }
    }
    stages {
        stage('Release') {
            steps {
                sh "git describe --exact-match --tags HEAD" // fails if HEAD commit is not tagged
                withCredentials([
                  string(credentialsId: "AnkaCloudGitlabExecutorGithubToken", variable: 'GITHUB_TOKEN'),
              ]) {
                    script {
                        docker.image('goreleaser/goreleaser:latest').inside('--entrypoint "" --env GOCACHE=/tmp/.gocache') {
                            sh 'goreleaser release --clean --snapshot'
                        }
                    }
              }
            }
        }
    }
    post { always {
        deleteDir()
    } }
}